### ISSUE TITLE
Deployment of API to Google Cloud Service

### ISSUE THREAD

**Issue by cskang0121** [cskang0121/flask-api-project#1]
##  Task List

- [x] Complete the [Deployment Tutorial](https://www.youtube.com/watch?v=3fsIcMgUOY8&t=23s)
- [x] Get familiarised with Google Cloud interface
- [x] Complete documentation for Deployment
